<?xml version="1.0"?>
<!DOCTYPE mensaje [
        <!ELEMENT mensaje (remite|destinatario|asunto|texto)*>
        <!ELEMENT remite (nombre|email)*>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT email (#PCDATA)>
        <!ELEMENT destinatario (nombre|email)*>
        <!ELEMENT asunto (#PCDATA)>
        <!ELEMENT texto (parrafo)*>
        <!ELEMENT parrafo (#PCDATA)>
        ]>
<mensaje>
    <remite>
        <nombre>Alfredo Reino</nombre>
        <email>alf@ibium.com</email>
    </remite>
    <destinatario>
        <nombre>Bill Clinton</nombre>
        <email>president@whitehouse.gov</email>
    </destinatario>
    <asunto>Hola Bill</asunto>
    <texto>
        <parrafo>¿Hola qué tal? Espero que estes bien, te extraño mucho, vamos a la plaza del estudiante.</parrafo>
    </texto>
</mensaje>
