<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE pedido [
        <!ELEMENT pedido (destinatario,articulo,direcci贸nEntrega,fechaEntrega)*>
        <!ELEMENT destinatario (#PCDATA)>
        <!ELEMENT articulo (#PCDATA)>
        <!ELEMENT direcci贸nEntrega (#PCDATA)>
        <!ELEMENT fechaEntrega (#PCDATA)>
        ]>

<pedido>
    <destinatario>Juan Delgado Martinez</destinatario>
    <articulo>Bicicleta Bianchi Oltre</articulo>
    <direcci贸nEntrega>Calle Reforma 423, tercer piso, letra A</direcci贸nEntrega>
    <fechaEntrega>19 - 09 - 2021</fechaEntrega>
</pedido>